{% set name = "transitkit" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: # Leave empty for now, will auto-fill

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - transitkit = transitkit.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pip
    # Optional dependencies
    - lightkurve
    - batman-package

test:
  imports:
    - transitkit
  commands:
    - transitkit --version
    - python -c "import transitkit; print(transitkit.__version__)"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/yourusername/transitkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Exoplanet Transit Light Curve Analysis Toolkit"
  description: |
    TransitKit is a comprehensive toolkit for analyzing exoplanet transit
    light curves from space missions like TESS, Kepler, and ground-based
    observatories.
  doc_url: https://transitkit.readthedocs.io
  dev_url: https://github.com/yourusername/transitkit

extra:
  recipe-maintainers:
    - yourgithubusername